// <auto-generated />
namespace Hospital_Management.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class hospital_management : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(hospital_management));
        
        string IMigrationMetadata.Id
        {
            get { return "202010031408176_hospital_management"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
